version: "3.6"
services: 
  nginx: 
    restart: on-failure
    build: ./nginx
    container_name: "nginx"
    ports: 
      - '8080:80'
      - '4443:443'
    volumes:
      - ./nginx/conf/:/etc/nginx/conf/
      - ./nginx/certs/:/etc/nginx/certs/
    networks:
      - main_network
  db:
    restart: on-failure
    env_file: .env
    build: ./mariadb
    container_name: "mariadb"
    environment:
      - MYSQL_DATABASE=${DB_HOST}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PSSWD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PSSWD}
      - MYSQL_ROOT=${DB_ROOT}
    volumes:
      - ./mariadb:/var/lib/mariadb
    networks:
      - main_network
  wordpress:
    restart: on-failure
    env_file: .env
    build: ./wordpress
    container_name: "wordpress"
    environment:
      - WORDPRESS_DB_HOST=${DB_HOST}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PSSWD}
      - WORDPRESS_DB_NAME=${DB_NAME}
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx/conf/:/etc/nginx/conf.d/
    depends_on:
    - db 
    - nginx
    networks:
      - main_network
volumes:
  wordpress:
  db:

networks:
  main_network:
    driver: bridge
    