version: "3.6"
services: 
  db:
    restart: on-failure
    env_file: .env
    build: ./requirements/mariadb 
    container_name: "mariadb"
    environment:
      - MYSQL_DATABASE=${DB_HOST}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PSSWD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PSSWD}
      - MYSQL_ROOT=${DB_ROOT}
      - DEBIAN_FRONTEND=noninteractive
    ports:
      - 3306:3306
    #volumes:
    # - /home/$USER/data/mariadb:/var/lib/mysql
    networks:
      - main_network
  wordpress:
    restart: on-failure
    env_file: .env
    # build: ./requirements/wordpress
    image: php-fpm:alpine
    container_name: "wordpress"
    ports: 
      - '9900:9000'
    environment:
      - WORDPRESS_DB_HOST=${DB_HOST}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PSSWD}
      - WORDPRESS_DB_NAME=${DB_NAME}
    volumes:
      - /home/massilia/data/wordpress:/var/www/html/wordpress:ro
    depends_on:
      - db 
    networks:
      - main_network
  nginx: 
    restart: on-failure
    build: ./requirements/nginx
    container_name: "nginx"
    ports: 
      - '8080:80'
      - '443:443'
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/conf
      - /home/massilia/data/wordpress:/var/www/html/wordpress
    networks:
      - main_network
    depends_on:
      - wordpress
volumes:
  wordpress:
  nginx:
  # db:

networks:
  main_network:    