version: '3'
services:
    db:
      restart: on-failure
      env_file: .env
      build: ./requirements/mariadb
      container_name: "mariadb"
      environment:
        - MYSQL_USER=${DB_USER}
        - MYSQL_PASSWORD=${DB_PSSWD}
        - MYSQL_ROOT_PASSWORD=${DB_ROOT_PSSWD}
      ports:
        - 3306:3306
      volumes:
        - mariadb:/var/lib/mysql
      networks:
        - back_network
    nginx:
        build: ./requirements/nginx
        container_name: "nginx"
        ports:
            - "8080:80"
            - "443:443"
        volumes:
            - wordpress:/var/www/html
            - ./requirements/nginx/conf/site.conf:/etc/nginx/conf.d/default.conf
        networks:
          - front_network
        depends_on:
          - wordpress
    wordpress:
      restart: on-failure
      env_file: .env
      build: ./requirements/wordpress
      ports:
        - "9000:9000"
      container_name: "wordpress"
      environment:
        - WORDPRESS_DB_USER=${DB_USER}
        - WORDPRESS_DB_PASSWORD=${DB_PSSWD}
        - WORDPRESS_DB_ROOT_PASSWORD=${DB_ROOT_PSSWD}
        - WORDPRESS_DB_NAME=${DB_NAME}
      volumes:
        - wordpress:/var/www/html
      networks:
        - front_network
        - back_network
      depends_on:
        - db
# volumes:
#   db:
#   wordpress:

# networks:
#     main_network:
#         driver: bridge
networks:
  front_network:
  back_network:

volumes: 
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/massilia/data/mariadb
  wordpress:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/massilia/data/wordpress