version: '2'
services:
    db:
      restart: on-failure
      env_file: .env
      build: ./requirements/mariadb
      container_name: "mariadb"
      environment:
        - MYSQL_DATABASE=${DB_HOST}
        - MYSQL_USER=${DB_USER}
        - MYSQL_PASSWORD=${DB_PSSWD}
        - MYSQL_ROOT_PASSWORD=${DB_ROOT_PSSWD}
        - MYSQL_ROOT=${DB_ROOT}
        - DEBIAN_FRONTEND=noninteractive
      ports:
        - 33306:3306
      volumes:
        - /home/user42/data/mariadb:/var/lib/mysql
      networks:
        - main_network
    nginx:
        build: ./requirements/nginx
        container_name: "nginx"
        ports:
            - "8080:80"
            - "443:443"
        volumes:
            - /home/user42/data/wordpress:/var/www/html
            - ./requirements/nginx/conf/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - main_network
        depends_on:
          - wordpress
    wordpress:
      restart: on-failure
      env_file: .env
      build: ./requirements/wordpress
      ports:
        - "9000:9000"
      container_name: "wordpress"
      environment:
        - WORDPRESS_DB_HOST=${DB_HOST}
        - WORDPRESS_DB_USER=${DB_USER}
        - WORDPRESS_DB_PASSWORD=${DB_PSSWD}
        - WORDPRESS_DB_NAME=${DB_NAME}
      volumes:
        - /home/user42/data/wordpress:/var/www/html
      networks:
        - main_network
      depends_on:
        - db
networks:
    main_network:
        driver: bridge