# version: "3.6"
# services: 
#   db:
#     restart: on-failure
#     env_file: .env
#     build: ./requirements/mariadb 
#     container_name: "mariadb"
#     environment:
#       - MYSQL_DATABASE=${DB_HOST}
#       - MYSQL_USER=${DB_USER}
#       - MYSQL_PASSWORD=${DB_PSSWD}
#       - MYSQL_ROOT_PASSWORD=${DB_ROOT_PSSWD}
#       - MYSQL_ROOT=${DB_ROOT}
#       - DEBIAN_FRONTEND=noninteractive
#     ports:
#       - 33306:3306
#     # volumes:
#     #  - /home/user42/data/mariadb:/var/lib/mysql
#     networks:
#       - main_network
#   wordpress:
#     restart: on-failure
#     env_file: .env
#     build: ./requirements/wordpress
#     # image: wordpress:5.1.1-fpm-alpine
#     container_name: "wordpress"
#     ports: 
#       - '9000:9000'
#     environment:
#       - WORDPRESS_DB_HOST=${DB_HOST}
#       - WORDPRESS_DB_USER=${DB_USER}
#       - WORDPRESS_DB_PASSWORD=${DB_PSSWD}
#       - WORDPRESS_DB_NAME=${DB_NAME}
#     volumes:
#       - /home/user42/data/wordpress:/var/www/html:ro
#     depends_on:
#       - db 
#     networks:
#       - main_network
#   nginx: 
#     restart: on-failure
#     build: ./requirements/nginx
#     # image: nginx:1.15.12-alpine
#     container_name: "nginx"
#     ports: 
#       - '8080:80'
#       - '443:443'
#     volumes:
#       - ./requirements/nginx/test/:/usr/share/nginx/html
#       - ./requirements/nginx/conf/:/etc/nginx/conf
#       - ./requirements/nginx/def/:/etc/nginx/sites-available
#       - /home/user42/data/wordpress:/var/www/html:ro
#     networks:
#       - main_network
#     depends_on:
#       - wordpress
# volumes:
#   wordpress:
#   nginx:
#   # db:

# networks:
#   main_network:
#      driver: bridge 
version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:fpm
        volumes:
            - ./code:/code
        networks:
            - code-network
networks:
    code-network:
        driver: bridge