version: '3'
services:
    db:
      restart: on-failure
      env_file: .env
      build: ./requirements/mariadb
      container_name: "mariadb"
      volumes:
        - mariadb:/var/lib/mysql
      networks:
        - network
    nginx:
      build: ./requirements/nginx
      container_name: "nginx"
      ports:
        - "443:443"
      volumes:
        - wordpress:/var/www/html
      networks:
        - network
      depends_on:
        - wordpress
    wordpress:
      restart: on-failure
      env_file: .env
      build: ./requirements/wordpress
      container_name: "wordpress"
      volumes:
        - wordpress:/var/www/html
      networks:
        - network
      depends_on:
        - db
networks:
  network:
    driver: bridge

volumes: 
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/user42/data/mariadb
  wordpress:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/user42/data/wordpress