CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS $MYSQL_ROOT@localhost IDENTIFIED BY '$MYSQL_PASSWORD';
SET PASSWORD FOR $MYSQL_ROOT@localhost = PASSWORD('$MYSQL_PASSWORD');
GRANT ALL ON *.* TO $MYSQL_ROOT@localhost WITH GRANT OPTION;